[package]
name = "cryptographer"
version = "0.1.1"
authors = ["Sammy <lixiangmin01@baidu.com>"]
edition = "2018"
description = "A Go-like crypto library in Rust"
documentation = "https://docs.rs/cryptographer"
homepage = "https://crates.io/crates/cryptographer"
license = "ISC"
repository = "https://github.com/sammyne/cryptographer.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
