# Rust CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/rust:1.40.0-buster

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: 
          name: version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - save_cache:
          paths: 
            # $CARGO_HOME
            - /usr/local/cargo
          key: cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run: 
          name: testing
          command: cargo test